### ISSUE TITLE
Como saber que version tengo

### ISSUE THREAD

**Issue by glbello** [open-source-uc/sincding#15]
Hola, quería saber como puedo ver que versión tengo del sincding ya que cada vez que realizo y sync, me avisa que hay una actualizacion disponible, trato de siempre de actualizar pero el mensaje me aparece siempre despues de ya haber actualizado, por lo que me lleva a pensar que el mensaje aparece siempre o es porque no he actualizado mi sincding de manera correcta

**Comment by negebauer** [comment]
Al correr sincding el mensaje de saludo tiene la versión

`npm install -g sincding` es para actualizarlo

Puedes ver la última versión con los tags del github y revisando el CHANGELOG.md

**Comment by glbello** [comment]
probado y verificado, te pasaste muchas gracias :D
