### ISSUE TITLE
Problemas unicode - Unicode Encoding Conflict

### ISSUE THREAD

**Issue by mandrade2** [open-source-uc/sincding#22]
### Describe your problem

hay conflicto con archivo llamado _9 - Almacenamiento - Índices - Algorítmos.pdf_ cada vez que hago sync se baja denuevo y guarda un archivo identico pero con nombre _9 - Almacenamiento - Índices - Algorítmos (Unicode Encoding Conflict (23)).pdf_ (en este momento tengo 23 copias). Supongo que es por los acentos.

### Attach log
```bash
Welcome to sincding!
Version 1.2.0

Current user data
user: mandrade2
path:
ignore: IIC2133

Executing 'sync' command
Starting login

.
.
.
Creating missing folders...

Starting downloads, this may take a while...
IIC2413 Downloaded file
Clases/9 - Almacenamiento - Índices - Algorítmos.pdf

Finished downloading!
```

**Comment by negebauer** [comment]
Estas guardando ese archivo en una carpeta de Dropbox?

**Comment by mandrade2** [comment]
si, bajo todo a un directorio en dropbox

**Comment by negebauer** [comment]
Me salió en Google que es un problema del manejo de caracteres de Dropbox

Puedes tratar borrando todas las copias del .pdf y luego correr sincding? (dale tiempo a dropbox de que haga sync y borre todo)

**Comment by mandrade2** [comment]
Efectivamente es dropbox. Cuando esta cerrado no baja denuevo el archivo. Cada vez que hago sincding sync con dropbox abierto se baja otra copia. Hay solución a esto o solo bajo a otra carpeta?

**Comment by negebauer** [comment]
Trata borrando el archivo en la página de dropbox, que desaparezca por completo
Y de ahí correr sync de nuevo
