### ISSUE TITLE
error de instalacion

### ISSUE THREAD

**Issue by mandrade2** [open-source-uc/sincding#3]
Por alguna razon no puedo instalarlo en ubuntu 16.04 LTS. He intendado borrandolo e instalndo denuevo e incluso con nodejs y npm tambien.  Alguna idea de que podria ser? Este error me arrroja
![screenshot from 2017-03-18 00-08-00](https://cloud.githubusercontent.com/assets/16262338/24068509/6026b790-0b6f-11e7-93a5-767e3b7b4ce7.png)

Saludos!

**Comment by negebauer** [comment]
Tu versión de node es muy vieja
Baja la 6 o 7 de la página de node (hay un link en el readme)

**Comment by mandrade2** [comment]
Ahi me funciono muchas gracias! 
Muy util!
