### ISSUE TITLE
Cómo puedo desintalar y volver instalar

### ISSUE THREAD

**Issue by glbello** [open-source-uc/sincding#31]
Tengo el problema que ahora ya no me reconoce los cursos del semestre actual, no había tenido problemas con el semestre anterior, intenté reiniciar los valores en `sincding data` pero no resultó

**Comment by negebauer** [comment]
```bash
npm remove -g sincding
npm i -g sincding
```

**Comment by glbello** [comment]
Muchísimas gracias c:

**Comment by negebauer** [comment]
Dale lo cierro 👌🏻
