### ISSUE TITLE
No me reconoce el semestre actual

### ISSUE THREAD

**Issue by glbello** [open-source-uc/sincding#33]
Saludos, tengo problemas que al momento de sincronizar, se me baja todo del semestre pasado y no el actual (II 2017)

**Comment by negebauer** [comment]
Actualizaste la versión?

**Comment by glbello** [comment]
Sip

**Comment by negebauer** [comment]
Tírate el log

**Comment by glbello** [comment]
¿Dónde saco eso?

**Comment by negebauer** [comment]
Lo que te imprime cuando lo corres

**Comment by glbello** [comment]
lo logré, al final cloné el repo y lo corrí desde el yarn, y ahí no tuve problemas, gracias de todos modos :)
