### ISSUE TITLE
SyntaxError index.js

### ISSUE THREAD

**Issue by glbello** [open-source-uc/sincding#39]
Instalé sincding en ubuntu, seguí todo lo inidicado en las instrucciones, al momento de ejecutar el comando sincding me aparece esto:

![captura de pantalla de 2017-09-19 00-18-21](https://user-images.githubusercontent.com/13740193/30574429-37d50a24-9cd0-11e7-92b9-b6229b82d84b.png)

¿Cómo lo soluciono?

**Comment by negebauer** [comment]
Revis tu versión de node `node -v` tiene que ser superior a 8

**Comment by glbello** [comment]
Revisaré, soy nuevo en ubuntu y tal vez por eso me salen estas cosas 😢

**Comment by glbello** [comment]
Lo logré, por si alguien es de utilidad, efectivamente tenía problemas con la versión del node, a través de este tuto, que con nvm instalé la última versión de node: https://gist.github.com/d2s/372b5943bce17b964a79
y ahora si funcionó sin problemas el sincding
