### ISSUE TITLE
File auto-update feature

### ISSUE THREAD

**Issue by mandrade2** [open-source-uc/sincding#42]
- [x] Installed node with version >= 8 (`node -v`)
- [x] Checked other issues

### Describe your problem

As a user of Sincding, I have to manually update the files that have been modified so I'm constantly downloading files whenever they are modified. I think it would be nice for the app to check whether modification dates between local and remote files match. If the remote file has a newer modification date then the user should be asked how to resolve the conflict because they can have work done on the file that can't be deleted. Otherwise keep the local file.

Right now I'm kind of busy but I can make a PR on December.

**Comment by negebauer** [comment]
Related #4
